# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1140811ff606138eefec2c1bd202005fd5627393561866e04fa46beba2668a80387a18f6832bce12ddd44a88a51dcf87eccee9b041048f2df1a8cfc2144d2ed

test:
  secret_key_base: 353ad23309d984b338aeaa18390831b794bf2cf15b07ddd27c9b3236520ac716b13c7ddbd9c4c2b4d2c4b81e5fadc62ca00436bb29a8ffa63555ac9c1dbdbce5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
